[project]
name = "python-template"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.10"

dependencies = [
    "python-telegram-bot==20.7",
    "requests",
    "flask",
    "Pillow"
]
